name: Development workflow

on:
  push:
    branches:
      - dev/CI-CD

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  PROJECT_NAME: CI-CDRPA                         
  PROJECT_FOLDER: CI-CD
  ORCH_URL: https://cloud.uipath.com/
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: ${{ secrets.UIPATHCLIENTID }}
  ORCH_USER_KEY: ${{ secrets.UIPATHUSERKEY }}
  ORCH_ACC_NAME: ${{ secrets.UIPATHACCOUNTNAME }}
  CLI_URL: https://uipath.visualstudio.com/Public.Feeds/_artifacts/feed/UiPath-Official/NuGet/UiPath.CLI.Windows/overview/23.10.8753.32995

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build-uipath-nuget-package:
    # You should be able to run on windows 2019 or windows latest
    needs: cleaner
    runs-on: windows-latest
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Build Nuget Package
        shell: pwsh
        run: ${{ github.workspace }}\Scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoversion
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
           package/*.*
           Scripts/*.ps1
  publish-uipath-nuget-package:
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts

      - name: Set Package Version
        id: set_version
        run: |
          $version = "$(Get-Date -Format 'yyyyMMdd.HHmmss')"
          Write-Host "Package version: $version"
          echo "::set-output name=version::$version"

      - name: Publish Nuget Package to DEV
        shell: pwsh
        run: |
          $packagePath = "${{ github.workspace }}/package"
          $orchestratorUrl = $env:ORCH_URL
          $tenant = $env:ORCH_TENANT
          $userKey = $env:ORCH_USER_KEY
          $accountName = $env:ORCH_ACC_NAME
          $version = $env:VERSION
          Write-Host "Package Path: $packagePath"
          Write-Host "Orchestrator URL: $orchestratorUrl"
          Write-Host "Tenant: $tenant"
          Write-Host "User Key: $userKey"
          Write-Host "Account Name: $accountName"
          Write-Host "Version: $version"
          .\Scripts\UiPathDeploy.ps1 $packagePath $orchestratorUrl $tenant -UserKey $userKey -account_name $accountName -Version $version
  
  

   
